{
 "title": "LLM Dashboard",
 "tags": [ "rayVersion:2.50.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "vllm_model_name",
    "label": "vLLM Model Name",
    "query": {
     "query": "label_values(vllm:request_prompt_tokens_sum{}, model_name)"
    }
   },
   {
    "name": "workerid",
    "label": "Worker ID",
    "query": {
     "query": "label_values(vllm:request_prompt_tokens_sum{}, WorkerId)"
    }
   },
   { "name": "interval", "label": "Interval" }
  ]
 },
 "panels": [
  {
   "title": "vLLM: Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tokens/s" } },
   "targets": [
    {
     "expr": "sum by (model_name, WorkerId) (rate(vllm:request_prompt_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Prompt Tokens/Sec - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "sum by (model_name, WorkerId) (rate(vllm:generation_tokens_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Generation Tokens/Sec - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Time per output token latency.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "(sum by(model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(vllm:time_per_output_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "Mean - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "GPU Cache Usage - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "vllm:cpu_cache_usage_perc{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "CPU Cache Usage - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by(model_name, WorkerId) (rate(vllm:time_to_first_token_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(vllm:time_to_first_token_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "Average - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId)(rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId)(rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId)(rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: E2E Request Latency",
   "type": "timeseries",
   "description": "Latency from request start to first token returned (in seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))\n/\nsum by(model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_count{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Average - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P50 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P90 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P95 - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name, WorkerId) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])))",
     "legendFormat": "P99 - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Running - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "vllm:num_requests_swapped{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Swapped - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "vllm:num_requests_waiting{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }",
     "legendFormat": "Num Waiting - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le, model_name, WorkerId) (increase(vllm:request_prompt_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vLLM: Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le, model_name, WorkerId) (increase(vllm:request_generation_tokens_bucket{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vLLM: Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(finished_reason, model_name, WorkerId) (increase(vllm:request_success_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{finished_reason}} - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(vllm:request_queue_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Requests Prefill and Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(vllm:request_decode_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Decode - {{model_name}} - {{WorkerId}}"
    },
    {
     "expr": "sum by(model_name, WorkerId) (rate(vllm:request_prefill_time_seconds_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "Prefill - {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Max Generation Token in Sequence Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by(model_name, WorkerId) (rate(vllm:request_max_num_generation_tokens_sum{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]))",
     "legendFormat": "{{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "vLLM: Prefix Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of prefix cache queries that resulted in a cache hit (GPU).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(vllm:gpu_prefix_cache_hits_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval]) / increase(vllm:gpu_prefix_cache_queries_total{model_name=~\"$vllm_model_name\", WorkerId=~\"$workerid\", }[$interval])",
     "legendFormat": "GPU: {{model_name}} - {{WorkerId}}"
    }
   ]
  },
  {
   "title": "Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "In: {{ model_name}}"
    },
    {
     "expr": "sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1w])) / sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "Out: {{ model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
     "legendFormat": "Input: {{model_name}}"
    },
    {
     "expr": "(sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1d])))",
     "legendFormat": "Generated: {{model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Input: {{model_name}}"
    },
    {
     "expr": "delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1h])",
     "legendFormat": "Generated: {{model_name}}"
    }
   ]
  },
  {
   "title": "Distribution of Requests Per Model Last 24 Hours",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Ratio Input:Generated Tokens Last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) / sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1d])) + sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1d]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Peak Tokens Per Second Per Model Last 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (model_name) (rate(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[2m]))[24h:])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Requests Per Model Last Week",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Last 7 Days",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) +\nsum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))) / sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Avg Total Tokens Per Request Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1w])) + sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1w])))/ sum by (model_name) (delta(vllm:request_success_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "{{ model_name}}"
    }
   ]
  },
  {
   "title": "Tokens Per Model Last 7 Days",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model_name) (delta(vllm:prompt_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "In: {{ model_name}}"
    },
    {
     "expr": "sum by (model_name) (delta(vllm:generation_tokens_total{WorkerId=~\"$workerid\", }[1w]))",
     "legendFormat": "Out: {{ model_name }}"
    }
   ]
  }
 ]
}