set -x

export NCCL_DEBUG=WARN
export WANDB_API_KEY=''
export VLLM_ATTENTION_BACKEND=XFORMERS
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=true
 
PROJECT_NAME=
EXPERIMENT_NAME=
DATA_PATH=
SFT_MODEL_PATH=
CKPT_PATH=

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files= \
 data.val_files= \
 data.train_batch_size=256 \
 data.val_batch_size=1024 \
 data.max_prompt_length=512 \
 data.max_response_length=256 \
 actor_rollout_ref.model.path= \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=64 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path= \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 +trainer.val_before_train=False \
 reward_model.reward_manager=generative \
 reward_model.reward_manager_config.server_url= \
 reward_model.reward_manager_config.model_name= \
 reward_model.reward_manager_config.scoring_prompt= \
 reward_model.reward_manager_config.num_samples=4 \
 reward_model.reward_manager_config.max_tokens=16 \
 reward_model.reward_manager_config.sc_mode=mean \
 reward_model.reward_manager_config.api_key= \
 reward_model.reward_manager_config.timeout=10 \
 reward_model.reward_manager_config.temperature=1.0 \
 reward_model.reward_manager_config.initial_concurrency=20 \
 reward_model.reward_manager_config.min_concurrency=10 \
 reward_model.reward_manager_config.max_concurrency=100 \
 reward_model.reward_manager_config.default_score=0.0 \
 reward_model.reward_manager_config.max_retries=3 \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=1 \
 trainer.nnodes=1 \
 trainer.save_freq=10 \
 trainer.test_freq=10 \
 trainer.total_epochs=15 2>&1 | tee verl_demo.log \
 trainer.logger=['console','wandb'] \
 trainer.project_name=$YOUR_PROJECT_NAME \
 trainer.experiment_name=$YOUR_RUN_NAME \