set -x

export NCCL_DEBUG=WARN
export WANDB_API_KEY='448ad9b79b563f75fbc01c9a69db00e98ffadae2'
export VLLM_ATTENTION_BACKEND=XFORMERS
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export TOKENIZERS_PARALLELISM=true
 
PROJECT_NAME='Qwen-1.5B-Test'
EXPERIMENT_NAME='Qwen_1.5B'
DATA_PATH=/mnt/petrelfs/fanyuchen
SFT_MODEL_PATH=/mnt/petrelfs/fanyuchen/Scaling-PRIME/Qwen/Qwen2.5-1.5B
CKPT_PATH=/mnt/petrelfs/fanyuchen/verl/ckpt

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=/cpfs01/shared/mascience/fanyuchen/editprm/verl/train.parquet \
 data.val_files=/cpfs01/shared/mascience/fanyuchen/editprm/verl/test.parquet \
 data.train_batch_size=256 \
 data.val_batch_size=1024 \
 data.max_prompt_length=512 \
 data.max_response_length=256 \
 actor_rollout_ref.model.path=/cpfs01/shared/mascience/fanyuchen/editprm/MODELS/Qwen2.5-0.5B-Instruct \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=64 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path=/cpfs01/shared/mascience/fanyuchen/editprm/MODELS/Qwen2.5-0.5B-Instruct \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 +trainer.val_before_train=False \
 reward_model.reward_manager=generative \
 reward_model.reward_manager_config.server_url=https://boyuerichdata.chatgptten.com/v1 \
 reward_model.reward_manager_config.model_name=deepseek-v3 \
 reward_model.reward_manager_config.scoring_prompt=/cpfs01/shared/mascience/fanyuchen/editprm/verl/verl/utils/prompts.txt \
 reward_model.reward_manager_config.num_samples=4 \
 reward_model.reward_manager_config.max_tokens=16 \
 reward_model.reward_manager_config.sc_mode=mean \
 reward_model.reward_manager_config.api_key=sk-CCjXe1pG7RMsNaAsjhoFKy9jiEJAoIG6bJOtROsJ618WvGBz \
 reward_model.reward_manager_config.timeout=10 \
 reward_model.reward_manager_config.temperature=1.0 \
 reward_model.reward_manager_config.initial_concurrency=20 \
 reward_model.reward_manager_config.min_concurrency=10 \
 reward_model.reward_manager_config.max_concurrency=100 \
 reward_model.reward_manager_config.default_score=0.0 \
 reward_model.reward_manager_config.max_retries=3 \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=1 \
 trainer.nnodes=1 \
 trainer.save_freq=10 \
 trainer.test_freq=10 \
 trainer.total_epochs=15 2>&1 | tee verl_demo.log \
 trainer.logger=['console','wandb'] \
 trainer.project_name=$YOUR_PROJECT_NAME \
 trainer.experiment_name=$YOUR_RUN_NAME \