working_dir: ./
excludes: ["/.git/"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  CUDA_LAUNCH_BLOCKING: "0"
  NVTE_DEBUG: "1"
  NVTE_DEBUG_LEVEL: "2"
  NVTE_FLASH_ATTN: "1" 
  RAY_DEBUG: "legacy"
  NCCL_DEBUG: "WARN"
  # NCCL_IB_DISABLE: "1"
  # NCCL_P2P_DISABLE: "1"
  NCCL_DEBUG_FILE: "/workspace/nccl_debug.log"
  # NCCL_SOCKET_IFNAME: "xgbe0"
  VLLM_USE_V1: "1"
  VERL_VLLM_DISTRIBUTED_BACKEND: "ray"


  # NVTE_UNFUSED_ATTN: "1"
  # If you are using vllm<=0.6.3, you might need to set the following environment variable to avoid bugs:
  # VLLM_ATTENTION_BACKEND: "XFORMERS"