tools:
  - class_name: "recipe.retool.retool.CustomSandboxFusionTool"
    config:
      sandbox_fusion_url: "http://localhost:8080/run_code"
      num_workers: 1
      enable_global_rate_limit: true
      rate_limit: 1
      default_timeout: 30
      default_language: "python"
      memory_limit_mb: 1024
      type: native

    tool_schema:
      type: "function"
      function:
        name: "execute"
        description: "Executes code using an IPython kernel and returns the output."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]

  - class_name: "recipe.retool.retool.SumbitTool"
    config:
      default_language: "python"
      memory_limit_mb: 1
      type: native

    tool_schema:
      type: "function"
      function:
        name: "submit"
        description: "Submits the solution to the puzzle."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "Executable code block containing the solution to the puzzle in the form of a Python function called `solution`, along with all imports and helper functions required by the `solution` function."
          required: ["code"]