FROM hiyouga/verl:ngc-th2.6.0-cu120-vllm0.8.2

RUN pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable

RUN cd /opt/nvidia && git clone --single-branch --branch v0.11.0 https://github.com/NVIDIA/Megatron-LM.git Megatron-LM

# only config pip index with https://pypi.tuna.tsinghua.edu.cn/simple if needed
# unset for now
RUN cd /opt/nvidia/Megatron-LM && pip3 install --no-deps -e .