FROM vllm/vllm-openai:v0.11.0

RUN pip install pybind11

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get -y install cudnn

RUN pip install nvidia-mathdx

RUN pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" git+https://github.com/NVIDIA/apex.git

RUN export NVTE_FRAMEWORK=pytorch && MAX_JOBS=128 NVTE_BUILD_THREADS_PER_JOB=4 pip3 install --resume-retries 999 --no-cache-dir --no-build-isolation git+https://github.com/NVIDIA/TransformerEngine.git@release_v2.8

RUN pip install --upgrade --no-cache-dir transformers tokenizers

RUN pip install codetiming tensordict mathruler pylatexenc qwen_vl_utils

RUN pip install flash_attn==2.8.1

RUN apt update && apt install numactl

RUN pip install -U git+https://github.com/ISEEKYAN/mbridge.git

RUN pip install --no-deps --no-cache-dir git+https://github.com/NVIDIA/Megatron-LM.git@core_v0.14.0rc7

RUN pip install git+https://github.com/volcengine/verl.git@v0.6.0