# docker buildx build -t "haibinlin/verl:th2.4.0-cu121-vllm0.5.4" -f docker/Dockerfile.th2.4.0 .

FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-devel

LABEL com.nvidia.volumes.needed="nvidia_driver"
LABEL com.nvidia.cuda.version=
ENV NVIDIA_VISIBLE_DEVICES= \
    NVIDIA_REQUIRE_CUDA="cuda>=11.0" \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

RUN apt-get update && apt-get install git vim -y

# install common libs
RUN pip3 install --no-cache-dir -U \
    ray==2.10.0 \
    transformers \
    accelerate \
    codetiming \
    dill \
    hydra-core \
    numpy \
    pybind11 \
    tensordict \
    transformers \
    flash-attn --no-build-isolation \
    vllm==0.5.4

# intall apex
WORKDIR /tmp/third_party

# install apex
# check their github repo for the latest installation command. the command changes from time to time.
RUN pip3 install -v --disable-pip-version-check --no-cache-dir --no-build-isolation \
    --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" \
    git+https://github.com/NVIDIA/apex

# install transformer engine v1.7
RUN pip3 install git+https://github.com/NVIDIA/TransformerEngine.git@v1.7

# install megatron
RUN pip3 install git+https://github.com/NVIDIA/Megatron-LM.git@core_v0.7.0

RUN pip3 install --no-cache-dir cupy-cuda12x

RUN rm -rf /tmp/third_party

