# Example Benchmax Tool Config
tools:
  # Class name points to benchmax class. This is expected to be a subclass of envs.BaseEnv
  - class_name: benchmax.envs.wikipedia.wiki_env.WikipediaEnv
    config:
      type: benchmax
      # Specify initialization args for Sandbox here e.g. api_keys
      # API keys are optional for the wikimedia environment but useful for higher API query limits.
      # api_keys:
      # - [API KEY 1]
      # - [API KEY 2]
      # You can find a guide to create wikimedia API keys here: https://api.wikimedia.org/wiki/Getting_started_with_Wikimedia_APIs