name: Type Annotation and Docstring Coverage

on:
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/type-coverage-check.yml'

jobs:
  type-coverage-check:
    runs-on: [L20x8]
    env:
      HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
      HTTPS_PROXY: ${{ secrets.PROXY_HTTPS }}
      NO_PROXY: "localhost,127.0.0.1"
      HF_HUB_ENABLE_HF_TRANSFER: 1
    container:
      image: verlai/verl:app-verl0.5-transformers4.55.4-sglang0.4.10.post2-mcore0.13.0-te2.2
      options: --gpus all --shm-size=10g
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 🚨 Important: fetch full history so `origin/main` is available
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gitpython
          pip install -e .[test]
      - name: Run type annotation coverage check
        run: |
          python3 tests/special_sanity/type_coverage_check.py
      - name: Run docstring coverage check
        run: |
          python3 tests/special_sanity/check_api_docs.py verl
